//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tour.DomainModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class LocationDetail
    {
        public int LocationDetails { get; set; }
        public string LocationTypeID { get; set; }
        public string LocationName { get; set; }
        public string LocationDescription { get; set; }
        public string LocationAddress1 { get; set; }
        public string LocationAddress2 { get; set; }
        public string LocationAddress3 { get; set; }
        public string LocationTown { get; set; }
        public string LocationCountyValue { get; set; }
        public string LocationEircode { get; set; }
        public string LocationEmail { get; set; }
        public string LocationPhone { get; set; }
        public string LocationURL { get; set; }
        public byte[] LocationImage { get; set; }
        public string LocationGPS { get; set; }
    }
}
