//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tour.DomainModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class LocationType
    {
        public int LocationTypeID { get; set; }
        public string LocationTypeDescription { get; set; }
    }
}
